apiVersion: v1
kind: Secret
metadata:
  name: {{ include "onitama.fullname" . }}-secrets
  labels:
    {{- include "onitama.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  {{- if .Values.secrets.databaseUrl }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  {{- else if .Values.postgresql.internal }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s-postgres:5432/%s" .Values.postgresql.user .Values.postgresql.password (include "onitama.fullname" .) .Values.postgresql.database | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.redisUrl }}
  REDIS_URL: {{ .Values.secrets.redisUrl | b64enc | quote }}
  {{- else if .Values.redis.internal }}
  REDIS_URL: {{ printf "redis://%s-redis:6379" (include "onitama.fullname" .) | b64enc | quote }}
  {{- end }}
  LOAD_TEST_KEY: {{ .Values.secrets.loadTestKey | b64enc | quote }}
